# Generated by Django 4.0.6 on 2022-11-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomeTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributoUm', models.CharField(max_length=100)),
                ('atributoDois', models.CharField(max_length=100)),
            ],
        ),
    ]
